---
development:
  dialect: "sqlite3"
  database: "./server/db/dev.sqlite3"

test:
  dialect: "sqlite3"
  database: "/tmp/test.sqlite3"

production:
  dialect: "sqlite3"
  database: "./server/db/production.sqlite3"
